name: API Automated Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: #

jobs:
  test-api:
    runs-on: ubuntu-latest
    # Añadimos la variable de entorno que sugiere GitHub para usar Node 24
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar Newman
        run: npm install -g newman npm install -g newman-reporter-htmlextra
        

      - name: Ejecutar pruebas de Postman
        run: newman run pokemon-get-200.json -r cli,htmlextra --reporter-htmlextra-export reporte.html
      - name: Caracteristicas pokemon
        run: newman run pokemon-caracteristicas-get-200.json -r cli,htmlextra --reporter-htmlextra-export reporte2.html

      - name: Subir reporte a GitHub
        uses: actions/upload-artifact@v4 # Asegura que estamos en el contexto correcto
        if: always() # Esto hace que el reporte se suba aunque los tests fallen
        with:
          name: reporte-de-pruebas
          path: reporte.html  

